src/INHack20/ControlDistribucionBundle/Entity/Tribunal.php
<?php

namespace INHack20\ControlDistribucionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * INHack20\ControlDistribucionBundle\Entity\Tribunal
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Tribunal
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer $nro
     *
     * @ORM\Column(name="nro", type="integer")
     */
    private $nro;

    /**
     *
     * @var boolean $habilitado
     * @ORM\Column(name="habilitado", type="boolean")
     */
    private $habilitado;
    
    /**
     *
     * @var boolean $despacho
     * @ORM\Column(name="despacho", type="boolean") 
     */
    private $despacho;
    
    /**
     *
     * @var TribunalTipo
     * @ORM\ManyToOne(targetEntity="TribunalTipo", inversedBy="tribunales")
     * @ORM\JoinColumn(name="tribunalTipo_id",referencedColumnName="id")
     */
    protected $tribunalTipo;
    
    /**
     *
     * @var Distribucion
     * @ORM\OneToMany(targetEntity="Distribucion",mappedBy="tribunal")
     */
    protected $distribuciones;
    
    /**
     *
     * @var Grupo
     * @ORM\ManyToOne(targetEntity="Grupo")
     * @ORM\JoinColumn(name="grupo_id",referencedColumnName="id") 
     */
    protected $grupo;
    
    public function __construct(){
        $this->distribuciones = new ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nro
     *
     * @param integer $nro
     */
    public function setNro($nro)
    {
        $this->nro = $nro;
    }

    /**
     * Get nro
     *
     * @return integer 
     */
    public function getNro()
    {
        return $this->nro;
    }

    /**
     * Set tribunalTipo
     *
     * @param INHack20\ControlDistribucionBundle\Entity\TribunalTipo $tribunalTipo
     */
    public function setTribunalTipo(\INHack20\ControlDistribucionBundle\Entity\TribunalTipo $tribunalTipo)
    {
        $this->tribunalTipo = $tribunalTipo;
    }

    /**
     * Get tribunalTipo
     *
     * @return INHack20\ControlDistribucionBundle\Entity\TribunalTipo 
     */
    public function getTribunalTipo()
    {
        return $this->tribunalTipo;
    }

    /**
     * Add distribuciones
     *
     * @param INHack20\ControlDistribucionBundle\Entity\Distribucion $distribuciones
     */
    public function addDistribucion(\INHack20\ControlDistribucionBundle\Entity\Distribucion $distribuciones)
    {
        $this->distribuciones[] = $distribuciones;
    }

    /**
     * Get distribuciones
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getDistribuciones()
    {
        return $this->distribuciones;
    }
    
    public function getDescripcion()
    {
        return ucwords($this->numeroToOrdinal($this->nro)) . ' De ' . $this->tribunalTipo->getNombre();
    }

    /**
     * Set habilitado
     *
     * @param boolean $habilitado
     */
    public function setHabilitado($habilitado)
    {
        $this->habilitado = $habilitado;
    }

    /**
     * Get habilitado
     *
     * @return boolean 
     */
    public function isHabilitado()
    {
        return $this->habilitado;
    }

    /**
     * Get habilitado
     *
     * @return boolean 
     */
    public function getHabilitado()
    {
        return $this->habilitado;
    }

    /**
     * Set despacho
     *
     * @param boolean $despacho
     */
    public function setDespacho($despacho)
    {
        $this->despacho = $despacho;
    }

    /**
     * Get despacho
     *
     * @return boolean 
     */
    public function isDespacho()
    {
        return $this->despacho;
    }

    /**
     * Get despacho
     *
     * @return boolean 
     */
    public function getDespacho()
    {
        return $this->despacho;
    }
    
    private function numeroToOrdinal($nro, $genero = 'M'){
        
        $l = 'o';
        if($genero == 'F')
            $l = 'a';
            
        $nrosOrdinalesFemeninos = array(
            0 => '',
            1 => 'primer'.$l,
            2 => 'segund'.$l,
            3 => 'tercer'.$l,
            4 => 'cuart'.$l,
            5 => 'quint'.$l,
            6 => 'sext'.$l,
            7 => 'septim'.$l,
            8 => 'octav'.$l,
            9 => 'noven'.$l,
            10 => 'decim'.$l,
            20 => 'vigesim'.$l,
            30 => 'trigesim'.$l,
            40 => 'cuadragesim'.$l,
            50 => 'quincuagesim'.$l,
            60 => 'sexagesim'.$l,
        );

        if($nro >= 0 && $nro<=10)
            {
                $nro = $nrosOrdinalesFemeninos[$nro];
            }
        elseif($nro >= 11 && $nro<=19){
                $nro = $nrosOrdinalesFemeninos[10] . ' ' . $nrosOrdinalesFemeninos[$nro - 10];
        }    
        elseif($nro >= 20 && $nro<=99){
                $resto = (floor($nro / 10)) * 10;
                $nro = $nrosOrdinalesFemeninos[$resto] . ' ' . $nrosOrdinalesFemeninos[$nro - $resto];
        }
        return $nro;
     }//fin funcion

    /**
     * Set grupo
     *
     * @param INHack20\ControlDistribucionBundle\Entity\Grupo $grupo
     */
    public function setGrupo(\INHack20\ControlDistribucionBundle\Entity\Grupo $grupo)
    {
        $this->grupo = $grupo;
    }

    /**
     * Get grupo
     *
     * @return INHack20\ControlDistribucionBundle\Entity\Grupo 
     */
    public function getGrupo()
    {
        return $this->grupo;
    }
}

src/INHack20/ControlDistribucionBundle/Form/TribunalType.php
<?php

namespace INHack20\ControlDistribucionBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class TribunalType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('nro',null,array(
                'label' => 'N&deg; Tribunal',
                'invalid_message' => 'Debe ingresar un numero entero',
                'error_bubbling' => false,
            ))
            ->add('tribunalTipo','entity',array(
                'class' => 'INHack20\\ControlDistribucionBundle\\Entity\\TribunalTipo',
                'property' => 'nombre',
                'label' => 'Tribunal de ',
                'empty_value' => 'Seleccione'
            ))
            ->add('despacho',null,array(
                'required' => false,
                'label' => '¿Hay Despacho?'
            ))
            ->add('grupo','entity',array(
                'label' => 'Grupo de Horario',
                'class' => 'INHack20\\ControlDistribucionBundle\\Entity\\Grupo',
                'property' => 'nombre',
                'empty_value' => 'Seleccione',
            ))
        ;
    }

    public function getName()
    {
        return 'inhack20_controldistribucionbundle_tribunaltype';
    }
}

src/INHack20/ControlDistribucionBundle/Controller/TribunalController.php
<?php

namespace INHack20\ControlDistribucionBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use INHack20\ControlDistribucionBundle\Entity\Tribunal;
use INHack20\ControlDistribucionBundle\Form\TribunalType;

/**
 * Tribunal controller.
 *
 * @Route("/configuracion/tribunal")
 */
class TribunalController extends Controller
{
    /**
     * Lists all Tribunal entities.
     *
     * @Route("/", name="tribunal")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entities = $em->getRepository('INHack20ControlDistribucionBundle:Tribunal')->findAll();

        return array('entities' => $entities);
    }

    /**
     * Finds and displays a Tribunal entity.
     *
     * @Route("/{id}/show", name="tribunal_show")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('INHack20ControlDistribucionBundle:Tribunal')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tribunal entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'status' => $this->getRequest()->query->get('status'),
            );
    }

    /**
     * Displays a form to create a new Tribunal entity.
     *
     * @Route("/new", name="tribunal_new")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Tribunal();
        $entity->setHabilitado(true);
        $form   = $this->createForm(new TribunalType(), $entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a new Tribunal entity.
     *
     * @Route("/create", name="tribunal_create")
     * @Method("post")
     * @Template("INHack20ControlDistribucionBundle:Tribunal:new.html.twig")
     */
    public function createAction()
    {
        $entity  = new Tribunal();
        $request = $this->getRequest();
        $form    = $this->createForm(new TribunalType(), $entity);
        $form->bindRequest($request);

        if ($form->isValid()) {
            $entity->setHabilitado(true);
            $em = $this->getDoctrine()->getEntityManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('tribunal_show', array('id' => $entity->getId(),
                'status' => $this->container->getParameter('EXITO_REGISTRO'),)));
            
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'status' => $this->container->getParameter('FALLO_REGISTRO'),
        );
    }

    /**
     * Displays a form to edit an existing Tribunal entity.
     *
     * @Route("/{id}/edit", name="tribunal_edit")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('INHack20ControlDistribucionBundle:Tribunal')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tribunal entity.');
        }

        $editForm = $this->createForm(new TribunalType(), $entity);
        $deleteForm = $this->createDeleteForm($id);
        
        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'status' => $this->getRequest()->query->get('status'),
        );
    }

    /**
     * Edits an existing Tribunal entity.
     *
     * @Route("/{id}/update", name="tribunal_update")
     * @Method("post")
     * @Template("INHack20ControlDistribucionBundle:Tribunal:edit.html.twig")
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('INHack20ControlDistribucionBundle:Tribunal')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tribunal entity.');
        }

        $editForm   = $this->createForm(new TribunalType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->getRequest();

        $editForm->bindRequest($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('tribunal_edit', array(
                'id' => $id,
                'status' => $this->container->getParameter('EXITO_ACTUALIZACION'),)));
        }
        
        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'status' => $this->container->getParameter('FALLO_ACTUALIZACION'),
        );
    }

    /**
     * Deletes a Tribunal entity.
     *
     * @Route("/{id}/delete", name="tribunal_delete")
     * @Method("post")
     */
    public function deleteAction($id)
    {
        $form = $this->createDeleteForm($id);
        $request = $this->getRequest();

        $form->bindRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();
            $entity = $em->getRepository('INHack20ControlDistribucionBundle:Tribunal')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Tribunal entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('tribunal'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/INHack20/ControlDistribucionBundle/Resources/views/Tribunal/edit.html.twig
{% extends 'INHack20ControlDistribucionBundle:Principal:index.html.twig' %}

{% block contenido %}
    <h1>Editar Tribunal</h1>
    <br/><br/>
    <fieldset>
         <legend>Datos</legend>
         <form id="frmGuardarCambios" action="{{ path('tribunal_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
                {{ form_widget(edit_form) }}
                <br/><br/>
                <p align="center">
                    <button type="submit" class="css3button">
                        <img src="{{ asset('bundles/inhack20controldistribucion/images/guardar.png') }}" width="16" height="16" alt="" />
                        Guardar Cambios</button>
                </p>
            </form>
            <form id="frmEliminar" action="{{ path('tribunal_delete', { 'id': entity.id }) }}" method="post">
                {{ form_widget(delete_form) }}
                    <button type="submit" class="css3button eliminar" style="float: right;">
                    <img src="{{ asset('bundles/inhack20controldistribucion/images/eliminar.png') }}" width="16" height="16" alt="" />                        
                    Eliminar</button>
            </form>
    </fieldset>     
{% endblock %}

src/INHack20/ControlDistribucionBundle/Resources/views/Tribunal/index.html.twig
{% extends 'INHack20ControlDistribucionBundle:Principal:index.html.twig' %}

{% block contenido %}
    <h1>Lista de Tribunales</h1>
    <br/><br/>
    <table class="tableCSS">
        <thead>
            <tr>
                <th>N&deg;</th>
                <th>Nro</th>
                <th>Grupo Horario</th>
                <th>¿Hay Despacho?</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr class="{% if loop.index % 2 == 0 %}even{% else %}odd{% endif %}">
                <td>{{ loop.index }}</td>
                <td>Tribunal {{ entity.descripcion | title }}</td>
                <td>
                    {{ entity.grupo.nombre }}
                </td>
                <td>
                    {% if entity.isdespacho %}
                        <font color="green">SI</font>
                    {% else %}
                        <font color="red">NO</font>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('tribunal_show', { 'id': entity.id }) }}">
                        <img src="{{ asset('bundles/inhack20controldistribucion/images/ver.png') }}" width="24" height="24" alt="" />
                    </a>
                    <a href="{{ path('tribunal_edit', { 'id': entity.id }) }}">
                        <img src="{{ asset('bundles/inhack20controldistribucion/images/editar.png') }}" width="24" height="24" alt="" />
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br/><br/>
    <p align="right">
                <a href="{{ path('tribunal_new') }}"><button id="btnBuscar" class="css3button" style="min-width: 10px">
                <img src="{{ asset('bundles/inhack20controldistribucion/images/registrar.png') }}" width="16" height="16" alt="" />
                Registrar</button></a>
    </p>
{% endblock %}

src/INHack20/ControlDistribucionBundle/Resources/views/Tribunal/new.html.twig
{% extends 'INHack20ControlDistribucionBundle:Principal:index.html.twig' %}

{% block contenido %}
    <h1>Registro de Tribunal</h1>
    <br/><br/><br/>
    <fieldset>
        <legend>Datos</legend>
        <form action="{{ path('tribunal_create') }}" method="post" {{ form_enctype(form) }}>
            {{ form_widget(form) }}
            <br/><br/>
            <p align="center">
                <button type="submit" class="css3button">Registrar</button>
            </p>
        </form>
    </fieldset>
{% endblock %}

src/INHack20/ControlDistribucionBundle/Resources/views/Tribunal/show.html.twig
{% extends 'INHack20ControlDistribucionBundle:Principal:index.html.twig' %}

{% block contenido %}
    <h1>Tribunal</h1>
    <br/><br/>
    <table class="tableCSS" style="width: auto">
        <thead>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            <tr class="even">
                <td>Id</td>
                <td>{{ entity.id }}</td>
            </tr>
            <tr class="odd">
                <td>N&deg;</td>
                <td>{{ entity.descripcion | title }}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </thead>
    </table>
    <br/><br/>
    <table>
        <tr>
            <td>
                <a href="{{ path('tribunal_edit',{'id' : entity.id }) }}">
                    <button class="css3button">
                        <img src="{{ asset('bundles/inhack20controldistribucion/images/editar.png') }}" width="16" height="16" alt="" />
                        Editar
                    </button>
                </a>
                    &nbsp;&nbsp;&nbsp;
            </td>
            <td>
                <form id="frmEliminar" action="{{ path('tribunal_delete', { 'id': entity.id }) }}" method="post">
                        <button class="css3button eliminar">
                            <img src="{{ asset('bundles/inhack20controldistribucion/images/eliminar.png') }}" width="16" height="16" alt="" />
                            Eliminar
                        </button>
                     {{ form_widget(delete_form) }}
                </form>
            </td>
            <td>&nbsp;&nbsp;&nbsp;</td>
        </tr>
    </table>
{% endblock %}